name: Real-estate Deployment

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Push and deploy
        run: cd /home/actions-runner && sudo bash verify.sh
